# Generated by Django 5.0.14 on 2025-11-13 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscripts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="manuscript",
            new_name="manuscripts_reposit_1e4af3_idx",
            old_name="manuscripts_reposit_idx",
        ),
        migrations.RenameIndex(
            model_name="manuscript",
            new_name="manuscripts_date_ea_0d0932_idx",
            old_name="manuscripts_date_ea_idx",
        ),
        migrations.RenameIndex(
            model_name="manuscript",
            new_name="manuscripts_created_06a14b_idx",
            old_name="manuscripts_created_idx",
        ),
        migrations.RenameIndex(
            model_name="manuscript",
            new_name="manuscripts_search__277ed4_gin",
            old_name="manuscripts_search__gin_idx",
        ),
        migrations.RenameIndex(
            model_name="surrogate",
            new_name="manuscripts_manuscr_e04d00_idx",
            old_name="manuscripts_manuscri_idx",
        ),
        migrations.RenameIndex(
            model_name="surrogate",
            new_name="manuscripts_created_fc6c69_idx",
            old_name="manuscripts_surrogate_created_idx",
        ),
    ]
