# Generated by Django 5.0.14 on 2025-11-13 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "manuscripts",
            "0002_rename_manuscripts_reposit_idx_manuscripts_reposit_1e4af3_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("point", "Point"),
                            ("rect", "Rectangle"),
                            ("polygon", "Polygon"),
                            ("circle", "Circle"),
                        ],
                        help_text="Type of annotation shape",
                        max_length=20,
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        help_text="Coordinates in format specific to annotation type"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short label for the annotation", max_length=255
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Category of annotation (e.g., 'heraldry', 'text', 'decoration')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the annotation"
                    ),
                ),
                ("related_arms_id", models.UUIDField(blank=True, null=True)),
                ("related_transcription_id", models.UUIDField(blank=True, null=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FF0000",
                        help_text="Hex color code for annotation display",
                        max_length=7,
                    ),
                ),
                (
                    "stroke_width",
                    models.IntegerField(default=2, help_text="Stroke width in pixels"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annotations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surrogate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="manuscripts.surrogate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotation",
                "verbose_name_plural": "Annotations",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["surrogate", "category"],
                        name="markup_anno_surroga_8381fb_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="markup_anno_created_1fcc07_idx"
                    ),
                ],
            },
        ),
    ]
